export const currenySymbolsOptions = [
 { label: "₹", value: "₹", selected: true },
  {id: 1, label: "$", value: "$" },
  {id: 2,  label: "€", value: "€" },
  {id: 3,  label: "£", value: "£" },
  {id: 4,  label: "¥", value: "¥" },
  {id: 5, label: "₽", value: "₽" },
  {id: 6,  label: "₩", value: "₩" },
  {id: 7, label: "₦", value: "₦" },
  {id: 8, label: "₪", value: "₪" },
//   {id:  label: "₫", value: "₫" },
//   {id:  label: "฿", value: "฿" },
//   {id:  label: "₴", value: "₴" },
//   {id:  label: "₲", value: "₲" },
//   {id:  label: "₵", value: "₵" },
//   {id:  label: "₺", value: "₺" },
//   {id:  label: "₡", value: "₡" },
//   {id:  label: "₱", value: "₱" },
//   {id:  label: "₭", value: "₭" },
//   {id:  label: "₨", value: "₨" },
].map((value) => ({
  value,
  label: value.label,
}));

export const currencyOptions = [
  { id: 1, label: "INR", value: "INR", selected: true },
  { id: 2, label: "USD", value: "USD" },
  { id: 3, label: "EUR", value: "EUR" },
  { id: 4, label: "GBP", value: "GBP" },
  { id: 5, label: "JPY", value: "JPY" },
  { id: 6, label: "RUB", value: "RUB" },
//   { label: "KRW", value: "KRW" },
//   { label: "NGN", value: "NGN" },
//   { label: "ILS", value: "ILS" },
//   { label: "VND", value: "VND" },
//   { label: "THB", value: "THB" },
//   { label: "UAH", value: "UAH" },
//   { label: "PLN", value: "PLN" },
//   { label: "COP", value: "COP" },
//   { label: "TRY", value: "TRY" },
//   { label: "ARS", value: "ARS" },
//   { label: "KZT", value: "KZT" },
//   { label: "KHR", value: "KHR" },
//   { label: "PKR", value: "PKR" },
].map((value) => ({
  value,
  label: value.label,
}));

